---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-releng-environments/oratos/ci-base

inputs:
- name: oratos-ci   # - This repo
- name: bbl-state
outputs:
- name: lb-ip

run:
  path: oratos-ci/tasks/expose-kubernetes-service/task

params:
  # - Required
  # - Code to run to setup kubectl to point to the cluster.
  GET_CREDENTIALS_HOOK:

  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
