#!/bin/bash
set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

mkdir -p $HOME/.kube
cp kube-config/config $HOME/.kube/config

kubectl patch service kubernetes \
    --namespace default \
    --patch '{"spec": {"type": "LoadBalancer"}}' \
    || true

count=1
echo -n "polling for lb ip address"
while true; do
    echo -n .
    ip="$(kubectl get service kubernetes \
            --namespace default \
            --output json \
            | jq .status.loadBalancer.ingress[0].ip --join-output)"
    if [ "$ip" != "null" ] && [ "$ip" != "" ]; then
        break
    fi
    if [ "$count" -gt 30 ]; then
        echo "unable to get service lb ip address"
        exit 1
    fi
    sleep 5
    ((count++))
done
echo "$ip" > lb-ip/ip
