# TODO CHANGE TO HAVE AN IMAGE THAT HAS OSSTCLIENTS
platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource
inputs:
- name: sink-resources
- name: fluent-bit-out-syslog
- name: oratos-ci # repo for task file
- name: osstpclients # repo containing the osstpclient binaries
params:
  # - Required
  # API Key is needed to upload and create tickets in OSM
  # This can be retrieved from: https://osm.eng.vmware.com/oss/#/user-settings
  OSM_API_CREDENTIALS:
run:
  path: oratos-ci/upload-go-osl/task
