#!/bin/bash

# shellcheck disable=SC1091
set -ex
REMAPPER="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/osstp.yaml

pip install -r osstpclients/etc/requirements.txt
OSSTP_LOAD="../osstpclients/bin/osstp-load.py"
OSM_API_CREDENTIALS_FILE=$(mktemp)
echo "$OSM_API_CREDENTIALS" > "$OSM_API_CREDENTIALS_FILE"

pushd osstptool
    make
popd

pushd sink-resources
    ../osstptool/osstptool generate -e sink-resources github.com/pivotal-cf/sink-resources --remapper-definitions-file="$REMAPPER"
    echo "y" | python "$OSSTP_LOAD" -R sink-resources-release/latest osstp_golang.yml -I "Distributed - Static Link w/ TP" -A "$OSM_API_CREDENTIALS_FILE"
popd

pushd fluent-bit-out-syslog
    ../osstptool/osstptool generate --vendor-path=vendor fluent-bit-out-syslog github.com/pivotal-cf/fluent-bit-out-syslog --remapper-definitions-file="$REMAPPER"
    echo "y" | python "$OSSTP_LOAD" -R sink-resources-release/latest osstp_golang.yml -I "Distributed - Static Link w/ TP" -A "$OSM_API_CREDENTIALS_FILE"
popd
