platform: linux
image_resource:
  type: docker-image
  source:
    repository: oratos/ci-base
inputs:
- name: oratos-ci
- name: namespace-drain
params:
  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
run:
  path: oratos-ci/tasks/latency-tests/task
