#!/bin/bash
set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

if [ -z "$ENV" ]; then
    echo ENV is required.
    exit 1
fi

function cleanup {
    set +e
    killall -9 ssh > /dev/null 2>&1
    killall -9 ssh-agent > /dev/null 2>&1
}
trap cleanup EXIT

BBL_STATE_DIR=bbl-state \
    oratos-ci/scripts/cfcr.sh "$ENV" get-credentials-tunnel

cp $HOME/.kube/config kube-config/config
