---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: oratos/ci-base

inputs:
- name: oratos-ci # - This repo
- name: bbl-state
outputs:
- name: kube-config

run:
  path: oratos-ci/tasks/cfcr-bbl-state-to-kube-config/task

params:
  # - Required
  # - The name of the cfcr environment.
  ENV:

  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
