#!/bin/bash
set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

if [ -z "$GET_CREDENTIALS_HOOK" ]; then
  echo GET_CREDENTIALS_HOOK must be set
  exit 1
fi

eval "$GET_CREDENTIALS_HOOK"

kubectl get namespaces --output json | \
  jq --raw-output .items[].metadata.name | \
  while read -r ns; do
    if [ "$ns" = "kube-system" ] || [ "$ns" = "default" ]; then
        continue
    fi
    kubectl --namespace "$ns" delete all --all --cascade --now || true
  done

kubectl --namespace kube-system delete all --all --cascade --now || true
kubectl --namespace default delete all --all --cascade --now || true
