---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: oratos/ci-base

inputs:
- name: oratos-ci               # - This repo
- name: bbl-state               # - Needed to have kubectl target env

run:
  path: oratos-ci/tasks/k8s-delete-all-resources/task

params:
  # - Required
  # - Code to run to setup kubectl to point to the cluster.
  GET_CREDENTIALS_HOOK:

  # - Required
  # - Address of vault server
  VAULT_ADDR:

  # - Required
  # - Vault role id for authentication
  ROLE_ID:

  # - Required
  # - Vault secret id for authentication
  SECRET_ID:

  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
