#!/bin/bash
set -e; [ -n "$DEBUG" ] && set -x

function teardown {
  set +e
  killall ssh
  killall ssh-agent
}
trap teardown EXIT

eval "$(ssh-agent)"

pushd deployments-loggregator/gcp/playground > /dev/null
  set +x
  source .envrc
  set +e
  source k8s_login
  set -e; [ -n "$DEBUG" ] && set -x

  kubectl get namespaces --output json | \
    jq --raw-output .items[].metadata.name | \
    while read ns; do
      kubectl --namespace "$ns" delete all --all --cascade --now
  done
popd > /dev/null

echo waiting for delete requests to complete
iterations=0
while true; do
  if [ "$iterations" -gt 15 ]; then
    echo "Polled too many times, failing"
    exit 1
  fi
  echo -n .
  count="$(
    kubectl get all --all-namespaces --output json | \
      jq --raw-output '.items | length'
  )"
  # kubernetes service might get recreated
  if [ -n "$count" ] || [ "$count" -lt 2 ]; then
    break
  fi
  sleep 5
  iterations+=1
done
