---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: oratos-ci          # - This repo
- name: deployments-loggregator # - Needed to have kubectl target env

run:
  path: oratos-ci/tasks/k8s-delete-all-resources/task

params:
  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
