#!/bin/bash
set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

if [ -z "$GET_CREDENTIALS_HOOK" ]; then
  echo GET_CREDENTIALS_HOOK must be set
  exit 1
fi

eval "$GET_CREDENTIALS_HOOK"

kubectl get namespaces --output json | \
  jq --raw-output .items[].metadata.name | \
  while read ns; do
    kubectl --namespace "$ns" delete all --all --cascade --now
  done

echo waiting for delete requests to complete
iterations=0
while true; do
  if [ "$iterations" -gt 15 ]; then
    echo "Polled too many times, failing"
    exit 1
  fi
  echo -n .
  count="$(
    kubectl get all --all-namespaces --output json | \
      jq --raw-output '.items | length'
  )"
  if [ -n "$count" ]; then
    # kubernetes service might get recreated, thus 2
    if ! [[ "$count" =~ '^[0-9]+$' ]] || [ "$count" -lt 2 ]; then
      break
    fi
  fi
  sleep 5
  iterations+=1
done
