apiVersion: v1
kind: Service
metadata:
  name: vault-nginx
  namespace: oratos-vault
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 443
  loadBalancerSourceRanges:
  # denver office
  - "50.232.79.0/30"
  - "205.168.109.120/29"

  # google cloud ip ranges, see: https://gist.github.com/n0531m/f3714f6ad6ef738a3b0a#gistcomment-2703576
  - "8.34.208.0/20"
  - "8.35.192.0/21"
  - "8.35.200.0/23"
  - "23.236.48.0/20"
  - "23.251.128.0/19"
  - "35.184.0.0/14"
  - "35.188.0.0/15"
  - "35.190.0.0/17"
  - "35.190.128.0/18"
  - "35.190.192.0/19"
  - "35.190.224.0/20"
  - "35.192.0.0/14"
  - "35.196.0.0/15"
  - "35.198.0.0/16"
  - "35.199.0.0/17"
  - "35.199.128.0/18"
  - "35.200.0.0/15"
  - "35.202.0.0/16"
  - "35.203.0.0/17"
  - "35.203.128.0/18"
  - "35.203.192.0/19"
  - "35.203.232.0/21"
  - "35.203.240.0/20"
  - "35.204.0.0/14"
  - "35.208.0.0/14"
  - "35.212.0.0/16"
  - "35.220.0.0/14"
  - "35.224.0.0/13"
  - "35.232.0.0/15"
  - "35.234.0.0/16"
  - "35.235.0.0/17"
  - "35.235.192.0/20"
  - "35.235.224.0/20"
  - "35.236.0.0/14"
  - "35.240.0.0/15"
  - "35.242.0.0/15"
  - "35.244.0.0/18"
  - "35.244.128.0/17"
  - "104.154.0.0/15"
  - "104.196.0.0/14"
  - "107.167.160.0/19"
  - "107.178.192.0/18"
  - "108.170.192.0/20"
  - "108.170.208.0/21"
  - "108.170.216.0/22"
  - "108.170.220.0/23"
  - "108.170.222.0/24"
  - "108.59.80.0/20"
  - "130.211.128.0/17"
  - "130.211.16.0/20"
  - "130.211.32.0/19"
  - "130.211.4.0/22"
  - "130.211.64.0/18"
  - "130.211.8.0/21"
  - "146.148.16.0/20"
  - "146.148.2.0/23"
  - "146.148.32.0/19"
  - "146.148.4.0/22"
  - "146.148.64.0/18"
  - "146.148.8.0/21"
  - "162.216.148.0/22"
  - "162.222.176.0/21"
  - "173.255.112.0/20"
  - "192.158.28.0/22"
  - "199.192.112.0/22"
  - "199.223.232.0/22"
  - "199.223.236.0/23"
  - "208.68.108.0/23"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: oratos-vault
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;

        keepalive_timeout  65;

        server {
            listen 443 ssl http2;
            listen [::]:443 ssl http2;

            ssl_certificate /vault-tls/tls.crt;
            ssl_certificate_key /vault-tls/tls.key;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;

            ssl_protocols TLSv1.2;
            ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
            ssl_prefer_server_ciphers on;

            add_header Strict-Transport-Security max-age=15768000;

            ssl_stapling on;

            location / {
                proxy_pass http://vault-vault.oratos-vault.svc.cluster.local:8200;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: oratos-vault
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command:
        - "nginx"
        - "-g"
        - "daemon off;"
        - "-c"
        - "/nginx-config/nginx.conf"
        ports:
        - containerPort: 443
        volumeMounts:
        - name: vault-tls
          mountPath: /vault-tls
          readOnly: true
        - name: nginx
          mountPath: /nginx-config
          readOnly: true
      volumes:
      - name: vault-tls
        secret:
          secretName: vault-tls
      - name: nginx
        configMap:
          name: nginx
