#!/bin/bash

set -e

if [ "$DEBUG" != "" ]; then
  set -x
fi

mkdir -p "workspace/src/$IMPORT_PATH"
cp -r source-repo/. "workspace/src/$IMPORT_PATH/"

mkdir -p ~/.ssh/
ssh-keyscan github.com >> ~/.ssh/known_hosts 2> /dev/null

pushd workspace > /dev/null
  export GOPATH="$PWD"
  export PATH="$GOPATH/bin:$PATH"

  pushd "src/$IMPORT_PATH" > /dev/null
    go get -t -d ./...
    eval "$PRE_TEST_HOOK"
    if [ "$PKGS_HOOK" != "" ]; then
      go test $(eval "$PKGS_HOOK") -race
    else
      go test ./... -race
    fi
    eval "$POST_TEST_HOOK"
  popd > /dev/null
popd > /dev/null
