apiVersion: apps/v1
kind: Deployment
metadata:
    name: telemetry-printer
    labels:
      app: telemetry-printer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-printer
  template:
    metadata:
      labels:
        app: telemetry-printer
    spec:
      containers:
      - name: telemetry-printer
        image: github.com/cloudfoundry-incubator/loggregator-tools/postprinter
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
kind: Service
apiVersion: v1
metadata:
  name: telemetry-printer
  annotations:
    cloud.google.com/app-protocols: '{"frontend":"HTTPS","frontend":"HTTP"}'
    service.alpha.kubernetes.io/app-protocols: '{"frontend":"HTTPS","frontend":"HTTP"}'
spec:
    type: NodePort
    selector:
      app: telemetry-printer
    ports:
      - name: telemetry-printer
        protocol: TCP
        port: 8080
        targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: telemetry-ingress
  annotations:
        kubernetes.io/ingress.global-static-ip-name: telemetry-ip
spec:
  backend:
    serviceName: telemetry-printer
    servicePort: 8080
