---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: oratos/ci-base

inputs:
- name: oratos-ci   # - This repo
- name: source-repo # - The Go package to test

run:
  path: oratos-ci/tasks/golangci-lint/task

params:
  # - Required
  # - The import path of the package to test.
  IMPORT_PATH:

  # - Optional
  # - Command that is ran to list packages to lint.
  # - Example: go list ./... | grep -v vendor | grep -v client
  PKGS_HOOK:

  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
