#!/bin/bash

set -ex

mkdir -p "workspace/src/$IMPORT_PATH"
cp -r source-repo/. "workspace/src/$IMPORT_PATH/"

mkdir -p ~/.ssh/
ssh-keyscan github.com >> ~/.ssh/known_hosts

pushd workspace
  export GOPATH="$PWD"
  export PATH="$GOPATH/bin:$PATH"

  pushd "src/$IMPORT_PATH"
    go get -t -d ./...
    golangci-lint run --deadline 2m
  popd
popd
