#!/bin/bash
set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

mkdir -p "workspace/src/$IMPORT_PATH"
cp -r source-repo/. "workspace/src/$IMPORT_PATH/"

mkdir -p ~/.ssh/
ssh-keyscan github.com >> ~/.ssh/known_hosts 2> /dev/null

pushd workspace > /dev/null
  export GOPATH="$PWD"
  export PATH="$GOPATH/bin:$PATH"

  pushd "src/$IMPORT_PATH" > /dev/null
    go get -t -d ./...
    if [ "$PKGS_HOOK" != "" ]; then
      golangci-lint run --deadline 20m $(eval "$PKGS_HOOK")
    else
      golangci-lint run --deadline 20m $(go list ./... | grep -v vendor)
    fi
  popd > /dev/null
popd > /dev/null
