---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: oratos/ci-base

inputs:
- name: oratos-ci   # - This repo
- name: source-repo # - The Go package to test

run:
  path: oratos-ci/tasks/golangci-lint/task

params:
  # - Required
  # - The import path of the package to test.
  IMPORT_PATH:
