#!/bin/bash
set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

source "oratos-ci/scripts/test/common.sh"

function clean_up_environment {
    bosh --deployment cfcr delete-deployment --non-interactive
}

function main {
    eval_bbl_state
    clean_up_environment
}

main
