#!/bin/bash
set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

source "oratos-ci/scripts/test/common.sh"

function clean_up_environment {
    bosh -d cfcr delete-deployment
}

function main {
    eval_bbl_state
    clean_up_environment
}

main
