apiVersion: apps/v1
kind: Deployment
metadata:
  name: logspewer
  labels:
    app: logspewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logspewer
  template:
    metadata:
      labels:
        app: logspewer
    spec:
      containers:
      - name: logspewer
        image: oratos/logspewer:v0.1

