groups:
- name: sink
  jobs:
  - sink-dripspinner
  - sink-flowspinner
  - sink-floodspinner
- name: loggregator-rlp
  jobs:
  - loggregator-rlp-dripspinner
  - loggregator-rlp-flowspinner
  - loggregator-rlp-floodspinner
- name: loggregator-syslog-nozzle
  jobs:
  - loggregator-syslog-nozzle-dripspinner
  - loggregator-syslog-nozzle-flowspinner
  - loggregator-syslog-nozzle-floodspinner

resource_types:
- name: vault
  type: docker-image
  source:
    repository: wfernandes/vault-resource
    tag: latest

resources:
- name: 15m
  type: time
  source:
    interval: 15m

- name: 1h
  type: time
  source:
    interval: 1h

- name: oratos-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master

- name: bikepark-bbl-state
  type: vault
  source:
    url: https://vault.oratos.ci.cf-app.com
    role_id: ((vault.role_id))
    secret_id: ((vault.secret_id))
    path: secret/envs/bikepark-bbl-state
    tarball: true

jobs:

##############################################################################
# LOGGREGATOR RLP BLACKBOX                                                   #
##############################################################################

- name: loggregator-rlp-floodspinner
  serial: true
  serial_groups: ["restage"]
  plan:
  - aggregate:
    - get: bikepark-bbl-state
    - get: oratos-ci
    - get: 15m
      trigger: true
  - task: run-test
    file: oratos-ci/tasks/loggregator-rlp-blackbox/task.yml
    input_mapping:
      bbl-state: bikepark-bbl-state
    params:
      SYSTEM_DOMAIN: bikepark.oratos.ci.cf-app.com
      GET_CREDENTIALS_HOOK: |
        BIKEPARK_BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/bikepark.sh get-credentials
      WAIT: 60
      CYCLES: 10000
      DATADOG_API_KEY: ((datadog.loggregator-ci-api-key))
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE"
    timeout: 15m

- name: loggregator-rlp-dripspinner
  serial: true
  serial_groups: ["restage"]
  plan:
  - aggregate:
    - get: bikepark-bbl-state
    - get: oratos-ci
    - get: 1h
      trigger: true
  - task: run-test
    file: oratos-ci/tasks/loggregator-rlp-blackbox/task.yml
    input_mapping:
      bbl-state: bikepark-bbl-state
    params:
      SYSTEM_DOMAIN: bikepark.oratos.ci.cf-app.com
      GET_CREDENTIALS_HOOK: |
        BIKEPARK_BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/bikepark.sh get-credentials
      WAIT: 600
      CYCLES: 1000
      DATADOG_API_KEY: ((datadog.loggregator-ci-api-key))
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
    timeout: 15m

- name: loggregator-rlp-flowspinner
  serial: true
  serial_groups: ["restage"]
  plan:
  - aggregate:
    - get: bikepark-bbl-state
    - get: oratos-ci
    - get: 1h
      trigger: true
  - task: run-test
    file: oratos-ci/tasks/loggregator-rlp-blackbox/task.yml
    input_mapping:
      bbl-state: bikepark-bbl-state
    params:
      SYSTEM_DOMAIN: bikepark.oratos.ci.cf-app.com
      GET_CREDENTIALS_HOOK: |
        BIKEPARK_BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/bikepark.sh get-credentials
      WAIT: 60
      CYCLES: 1000
      DATADOG_API_KEY: ((datadog.loggregator-ci-api-key))
      DELAY: "1"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
    timeout: 15m

##############################################################################
# LOGGREGATOR SYSLOG NOZZLE BLACKBOX                                         #
##############################################################################

- name: loggregator-syslog-nozzle-floodspinner
  serial: true
  serial_groups: ["restage"]
  plan:
  - aggregate:
    - get: bikepark-bbl-state
    - get: oratos-ci
    - get: 15m
      trigger: true
  - task: run-test
    file: oratos-ci/tasks/loggregator-syslog-nozzle-blackbox/task.yml
    input_mapping:
      bbl-state: bikepark-bbl-state
    params:
      SYSTEM_DOMAIN: bikepark.oratos.ci.cf-app.com
      GET_CREDENTIALS_HOOK: |
        BIKEPARK_BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/bikepark.sh get-credentials
      PAPERTRAIL_TOKEN: ((papertrail.token))
      PAPERTRAIL_DESTINATION: ((papertrail.addr))
      WAIT: 60
      CYCLES: 10000
      DATADOG_API_KEY: ((datadog.loggregator-ci-api-key))
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE"
    timeout: 15m

- name: loggregator-syslog-nozzle-dripspinner
  serial: true
  serial_groups: ["restage"]
  plan:
  - aggregate:
    - get: bikepark-bbl-state
    - get: oratos-ci
    - get: 1h
      trigger: true
  - task: run-test
    file: oratos-ci/tasks/loggregator-syslog-nozzle-blackbox/task.yml
    input_mapping:
      bbl-state: bikepark-bbl-state
    params:
      SYSTEM_DOMAIN: bikepark.oratos.ci.cf-app.com
      GET_CREDENTIALS_HOOK: |
        BIKEPARK_BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/bikepark.sh get-credentials
      PAPERTRAIL_TOKEN: ((papertrail.token))
      PAPERTRAIL_DESTINATION: ((papertrail.addr))
      WAIT: 600
      CYCLES: 1000
      DATADOG_API_KEY: ((datadog.loggregator-ci-api-key))
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
    timeout: 15m

- name: loggregator-syslog-nozzle-flowspinner
  serial: true
  serial_groups: ["restage"]
  plan:
  - aggregate:
    - get: bikepark-bbl-state
    - get: oratos-ci
    - get: 1h
      trigger: true
  - task: run-test
    file: oratos-ci/tasks/loggregator-syslog-nozzle-blackbox/task.yml
    input_mapping:
      bbl-state: bikepark-bbl-state
    params:
      SYSTEM_DOMAIN: bikepark.oratos.ci.cf-app.com
      GET_CREDENTIALS_HOOK: |
        BIKEPARK_BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/bikepark.sh get-credentials
      PAPERTRAIL_TOKEN: ((papertrail.token))
      PAPERTRAIL_DESTINATION: ((papertrail.addr))
      WAIT: 60
      CYCLES: 1000
      DATADOG_API_KEY: ((datadog.loggregator-ci-api-key))
      DELAY: "1"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
    timeout: 15m

##############################################################################
# SINK BLACKBOX                                                              #
##############################################################################

- name: sink-floodspinner
  serial: true
  serial_groups: ["restage"]
  plan:
  - aggregate:
    - get: bikepark-bbl-state
    - get: oratos-ci
    - get: 15m
      trigger: true
  - task: run-test
    file: oratos-ci/tasks/sink-blackbox/task.yml
    input_mapping:
      bbl-state: bikepark-bbl-state
    params:
      SYSTEM_DOMAIN: bikepark.oratos.ci.cf-app.com
      GET_CREDENTIALS_HOOK: |
        BIKEPARK_BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/bikepark.sh get-credentials
      PAPERTRAIL_TOKEN: ((papertrail.token))
      PAPERTRAIL_DESTINATION: ((papertrail.addr))
      WAIT: 60
      CYCLES: 10000
      DATADOG_API_KEY: ((datadog.loggregator-ci-api-key))
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE"
    timeout: 15m

- name: sink-dripspinner
  serial: true
  serial_groups: ["restage"]
  plan:
  - aggregate:
    - get: bikepark-bbl-state
    - get: oratos-ci
    - get: 1h
      trigger: true
  - task: run-test
    file: oratos-ci/tasks/sink-blackbox/task.yml
    input_mapping:
      bbl-state: bikepark-bbl-state
    params:
      SYSTEM_DOMAIN: bikepark.oratos.ci.cf-app.com
      GET_CREDENTIALS_HOOK: |
        BIKEPARK_BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/bikepark.sh get-credentials
      PAPERTRAIL_TOKEN: ((papertrail.token))
      PAPERTRAIL_DESTINATION: ((papertrail.addr))
      WAIT: 600
      CYCLES: 1000
      DATADOG_API_KEY: ((datadog.loggregator-ci-api-key))
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
    timeout: 15m

- name: sink-flowspinner
  serial: true
  serial_groups: ["restage"]
  plan:
  - aggregate:
    - get: bikepark-bbl-state
    - get: oratos-ci
    - get: 1h
      trigger: true
  - task: run-test
    file: oratos-ci/tasks/sink-blackbox/task.yml
    input_mapping:
      bbl-state: bikepark-bbl-state
    params:
      SYSTEM_DOMAIN: bikepark.oratos.ci.cf-app.com
      GET_CREDENTIALS_HOOK: |
        BIKEPARK_BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/bikepark.sh get-credentials
      PAPERTRAIL_TOKEN: ((papertrail.token))
      PAPERTRAIL_DESTINATION: ((papertrail.addr))
      WAIT: 60
      CYCLES: 1000
      DATADOG_API_KEY: ((datadog.loggregator-ci-api-key))
      DELAY: "1"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
    timeout: 15m
