groups:
- name: ci
  jobs:
  - ci-base
- name: test-images
  jobs:
  - crosstalk-receiver
  - latency-receiver
- name: builder-images
  jobs:
  - golang-base

resources:
- name: base-image-docker-build-context
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master
    paths:
    - docker-images/ci-base

- name: golang-base-image-docker-build-context
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master
    paths:
    - docker-images/golang-base

- name: golang-base-image
  type: docker-image
  source:
    repository: oratos/golang-base
    username: ((docker-hub.username))
    password: ((docker-hub.password))
    tag: 1.11

- name: ci-base-image
  type: docker-image
  source:
    repository: oratos/ci-base
    username: ((docker-hub.username))
    password: ((docker-hub.password))

- name: crosstalk-receiver-image
  type: docker-image
  source:
    repository: oratos/crosstalk-receiver
    username: ((docker-hub.username))
    password: ((docker-hub.password))

- name: latency-receiver-image
  type: docker-image
  source:
    repository: oratos/latency-receiver
    username: ((docker-hub.username))
    password: ((docker-hub.password))

- name: oratos-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master

jobs:
- name: golang-base
  plan:
  - get: golang-base-image-docker-build-context
    trigger: true
  - put: golang-base-image
    params:
      build: golang-base-image-docker-build-context/docker-images/golang-base
      tag_as_latest: true
      cache_tag: 1.11
    get_params:
      skip_download: true

- name: ci-base
  plan:
  - get: base-image-docker-build-context
    trigger: true
  - put: ci-base-image
    params:
      build: base-image-docker-build-context/docker-images/ci-base
      tag_as_latest: true
      cache_tag: latest
    get_params:
      skip_download: true

- name: crosstalk-receiver
  plan:
  - get: oratos-ci
  - task: write-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      params:
        VERSION: v0.1
        DEBUG:
      outputs:
      - name: tags
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

          echo "$VERSION" > tags/version
  - put: crosstalk-receiver-image
    params:
      build: oratos-ci/tools/syslog-receiver
      dockerfile: oratos-ci/tools/syslog-receiver/cmd/crosstalk-receiver/Dockerfile
      tag_as_latest: true
      tag: tags/version
      cache_tag: latest
    get_params:
      skip_download: true

- name: latency-receiver
  plan:
  - get: oratos-ci
  - task: write-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      params:
        VERSION: v0.1
        DEBUG:
      outputs:
      - name: tags
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

          echo "$VERSION" > tags/version
  - put: latency-receiver-image
    params:
      build: oratos-ci/tools/syslog-receiver
      dockerfile: oratos-ci/tools/syslog-receiver/cmd/latency-receiver/Dockerfile
      tag_as_latest: true
      tag: tags/version
      cache_tag: latest
    get_params:
      skip_download: true
