resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: oratos-ci
  type: git
  source:
    uri: https://github.com/oratos/ci
    branch: master

- name: out-syslog
  type: git
  source:
    uri: https://github.com/oratos/out_syslog
    branch: master

- name: out-syslog-dockerfile
  type: git
  source:
    uri: https://github.com/oratos/ci
    branch: master
    paths:
    - docker-images/fluent-bit-out-syslog

- name: out-syslog-image
  type: docker-image
  source:
    repository: oratos/fluent-bit-out-syslog
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-url}}

jobs:
- name: unit-tests
  public: false
  serial: true
  plan:
  - aggregate:
    - get: out-syslog
      trigger: true
    - get: oratos-ci
  - task: run-linter
    file: oratos-ci/tasks/golangci-lint/task.yml
    input_mapping:
      source-repo: out-syslog
    params:
      IMPORT_PATH: github.com/oratos/out_syslog
    on_failure:
      put: slack-alert
      params:
        text: Syslog Plugin Linter failed

  - task: run-tests
    file: oratos-ci/tasks/go-test-with-latest-packages/task.yml
    input_mapping:
      source-repo: out-syslog
    params:
      IMPORT_PATH: github.com/oratos/out_syslog
    on_failure:
      put: slack-alert
      params:
        text: Syslog Plugin Unit tests failed

- name: build-out-syslog
  public: false
  serial: true
  plan:
  - aggregate:
    - get: out-syslog
      trigger: true
      passed:
      - unit-tests
    - get: out-syslog-dockerfile
      trigger: true
    - get: oratos-ci
  - task: prepare-build
    file: oratos-ci/tasks/build-go-docker-image/task.yml
    input_mapping:
      context-repo: out-syslog-dockerfile
      source-repo: out-syslog
    params:
      CONTEXT_PATH: docker-images/fluent-bit-out-syslog
      BASE_PACKAGE: github.com/oratos/out_syslog
  - put: out-syslog-image
    params:
      build: build-image/build
      tag: build-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest
