groups:
- name: main
  jobs:
  - unit-tests
  - build-fluent-bit-out-syslog-image
  - release

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: oratos-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master

- name: out-syslog
  type: git
  source:
    uri: git@github.com:pivotal-cf/fluent-bit-out-syslog
    branch: master
    private_key: ((github.oratos-bot-private-key))

- name: out-syslog-github-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: fluent-bit-out-syslog
    access_token: ((github.oratos-bot-release-access-token))
    release: false
    pre_release: true

- name: fluent-bit-out-syslog-image
  type: docker-image
  source:
    repository: ((docker_image_repository))/fluent-bit-out-syslog
    username: ((artifactory.username))
    password: ((artifactory.password))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack.notifications-url))

jobs:
- name: unit-tests
  plan:
  - in_parallel:
    - get: out-syslog
      trigger: true
    - get: oratos-ci
  - in_parallel:
    - task: run-linter
      file: oratos-ci/tasks/golangci-lint-modules/task.yml
      input_mapping:
        source-repo: out-syslog
      on_failure:
        put: slack-alert
        params:
          text: Syslog Plugin Linter failed
    - task: run-tests
      file: oratos-ci/tasks/go-test-mod/task.yml
      privileged: true
      input_mapping:
        source-repo: out-syslog
      params:
      on_failure:
        put: slack-alert
        params:
          text: Syslog Plugin Unit tests failed

- name: build-fluent-bit-out-syslog-image
  serial: true
  plan:
  - in_parallel:
    - get: out-syslog
      trigger: true
      passed:
      - unit-tests
    - get: oratos-ci
  - in_parallel:
    - task: prepare-build
      file: oratos-ci/tasks/build-docker-image/task.yml
      input_mapping:
        source-repo: out-syslog
      params:
        CONTAINER_REPOSITORY: ((docker_image_repository))
        BASE_IMAGE: ((base_image))
        GOLANG_SOURCE: ((golang_source))
        KUBECTL_SOURCE: ((kubectl_source))
  - put: fluent-bit-out-syslog-image
    params:
      build_args_file: build-image/docker_build_args
      build: build-image/build
      tag: build-image/tag
    get_params:
      skip_download: true

- name: release
  serial: true
  plan:
  - get: out-syslog
    passed:
    - build-fluent-bit-out-syslog-image
  - task: prepare-out-syslog-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      params:
        VERSION: ((fluent_bit_out_syslog_params.VERSION))
      inputs:
      - name: out-syslog
      outputs:
      - name: github-release
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          echo "$VERSION" > github-release/name
          echo "$VERSION" > github-release/tag

          SHA="$(cd out-syslog && git rev-parse @)"
          echo "$SHA" > github-release/sha
  - put: out-syslog-github-release
    params:
      name: github-release/name
      tag: github-release/tag
      commitish: github-release/sha