groups:
- name: main
  jobs:
  - latency-tests

resource_types:
- name: vault
  type: docker-image
  source:
    repository: wfernandes/vault-resource
    tag: latest

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: oratos-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master

- name: namespace-drain
  type: git
  source:
    uri: git@github.com:pivotal-cf/namespace-drain
    branch: master
    private_key: ((github.oratos-bot-private-key))

jobs:
- name: latency-tests
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
    - get: oratos-ci
  - task: run-test
    file: oratos-ci/tasks/latency-tests/task.yml
    input_mapping:
      source-repo: namespace-drain
    params:
      IMPORT_PATH: github.com/pivotal-cf/namespace-drain
