resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: vault
  type: docker-image
  source:
    repository: wfernandes/vault-resource
    tag: latest

resources:
- name: oratos-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master

- name: namespace-drain
  type: git
  source:
    uri: git@github.com:pivotal-cf/namespace-drain
    branch: master
    private_key: ((github.oratos-bot-private-key))

- name: sink-controller-dockerfile
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master
    paths:
    - docker-images/sink-controller

- name: sink-controller-image
  type: docker-image
  source:
    repository: oratos/sink-controller
    username: ((docker-hub.username))
    password: ((docker-hub.password))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack.notifications-url))

- name: oratos-ci-testing-cfcr-bbl-state
  type: vault
  source:
    url: https://vault.oratos.ci.cf-app.com
    role_id: ((vault.role_id))
    secret_id: ((vault.secret_id))
    path: secret/envs/oratos-ci-testing-cfcr-bbl-state
    tarball: true

jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
    - get: oratos-ci
  - aggregate:
    - task: run-linter
      file: oratos-ci/tasks/golangci-lint/task.yml
      input_mapping:
        source-repo: namespace-drain
      params:
        IMPORT_PATH: github.com/pivotal-cf/namespace-drain
        PKGS_HOOK: |
          go list ./... | grep -v vendor | grep -v pkg/client | sed 's|github.com/pivotal-cf/namespace-drain/||'
      on_failure:
        put: slack-alert
        params:
          text: Namespace Drain Linter failed
    - task: run-tests
      file: oratos-ci/tasks/go-test-with-latest-packages/task.yml
      privileged: true
      input_mapping:
        source-repo: namespace-drain
      params:
        IMPORT_PATH: github.com/pivotal-cf/namespace-drain
        PKGS_HOOK: |
          go list ./... | grep -v vendor | grep -v pkg/client
      on_failure:
        put: slack-alert
        params:
          text: Namespace Drain Unit tests failed
    - task: run-verify-codegen
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: oratos/ci-base
        inputs:
        - name: namespace-drain
        params:
          DEBUG:
        run:
          path: /bin/bash
          args:
          - "-c"
          - |
            #!/bin/bash
            set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

            export GOPATH="$PWD/workspace"
            path=workspace/src/github.com/pivotal-cf/namespace-drain
            mkdir -p "$path"
            cp -r namespace-drain/. "$path/"
            cd "$path"
            hack/verify-codegen.sh
      on_failure:
        put: slack-alert
        params:
          text: Namespace Drain Verify Codegen failed

- name: build-sink-controller-image
  serial: true
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
      passed:
      - unit-tests
    - get: sink-controller-dockerfile
      trigger: true
    - get: oratos-ci
  - task: prepare-build
    file: oratos-ci/tasks/build-go-docker-image/task.yml
    input_mapping:
      context-repo: sink-controller-dockerfile
      source-repo: namespace-drain
    params:
      CONTEXT_PATH: docker-images/sink-controller
      BASE_PACKAGE: github.com/pivotal-cf/namespace-drain
  - put: sink-controller-image
    params:
      build: build-image/build
      tag_file: build-image/tag
      cache: true
      cache_tag: latest
    get_params:
      skip_download: true

- name: deploy-gke
  serial: true
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
      passed:
      - build-sink-controller-image
    - get: sink-controller-image
      trigger: true
      passed:
      - build-sink-controller-image
      params:
        skip_download: true
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      inputs:
      - name: namespace-drain
      - name: sink-controller-image
      params:
        SERVICE_ACCOUNT: ((gcloud.oratos-ci-testing-gke-service-account))
        DEBUG:
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

          echo "$SERVICE_ACCOUNT" > sa.json
          gcloud auth activate-service-account --key-file sa.json
          rm sa.json
          gcloud container clusters get-credentials oratos-ci-testing \
            --zone us-central1-a

          sha="$(cat sink-controller-image/tag)"
          yq read namespace-drain/manifests/05-deployments/sink.yml --tojson | \
            jq '(.spec.template.spec.containers[] | select(.name == "sink-controller")).image = "oratos/sink-controller:'"$sha"'"' \
            > namespace-drain/manifests/05-deployments/sink.json
          rm namespace-drain/manifests/05-deployments/sink.yml
          kubectl apply -R -f namespace-drain/manifests
          patch='{"spec": {"template": {"metadata": {"labels": {"randomversion": "'$RANDOM'"}}}}}'
          kubectl patch -R -f namespace-drain/manifests --patch "$patch"

- name: crd-tests
  serial: true
  plan:
  - aggregate:
    - get: sink-controller-image
      trigger: true
      passed:
      - deploy-gke
      params:
        skip_download: true
    - get: namespace-drain
      trigger: true
  - task: run-crd-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      inputs:
      - name: namespace-drain
      params:
        SERVICE_ACCOUNT: ((gcloud.oratos-ci-testing-gke-service-account))
        DEBUG:
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

          echo "$SERVICE_ACCOUNT" > sa.json
          gcloud auth activate-service-account --key-file sa.json
          rm sa.json
          gcloud container clusters get-credentials oratos-ci-testing \
            --zone us-central1-a

          namespace-drain/tests/test.sh

- name: deploy-cfcr
  serial: true
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
      passed:
      - build-sink-controller-image
    - get: sink-controller-image
      trigger: true
      passed:
      - build-sink-controller-image
      params:
        skip_download: true
    - get: oratos-ci-testing-cfcr-bbl-state
    - get: oratos-ci
  - task: deploy
    input_mapping:
      bbl-state: oratos-ci-testing-cfcr-bbl-state
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      inputs:
      - name: namespace-drain
      - name: sink-controller-image
      - name: oratos-ci
      - name: bbl-state
      params:
        DEBUG:
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

          BBL_STATE_DIR=bbl-state \
              oratos-ci/scripts/cfcr.sh testing get-credentials

          sha="$(cat sink-controller-image/tag)"
          yq read namespace-drain/manifests/05-deployments/sink.yml --tojson | \
            jq '(.spec.template.spec.containers[] | select(.name == "sink-controller")).image = "oratos/sink-controller:'"$sha"'"' \
            > namespace-drain/manifests/05-deployments/sink.json
          rm namespace-drain/manifests/05-deployments/sink.yml
          kubectl apply -R -f namespace-drain/manifests
          patch='{"spec": {"template": {"metadata": {"labels": {"randomversion": "'$RANDOM'"}}}}}'
          kubectl patch -R -f namespace-drain/manifests --patch "$patch"

- name: crosstalk-test
  serial: true
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
      passed:
      - deploy-cfcr
    - get: oratos-ci
    - get: oratos-ci-testing-cfcr-bbl-state
  - task: crosstalk-test
    file: oratos-ci/tasks/sink-crosstalk/task.yml
    input_mapping:
      bbl-state: oratos-ci-testing-cfcr-bbl-state
    params:
      GET_CREDENTIALS_HOOK: |
        BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/cfcr.sh testing get-credentials
      NAOMI_A_CERT: ((crosstalk.naomi_a_cert))
      NAOMI_A_KEY: ((crosstalk.naomi_a_key))
      NAOMI_B_CERT: ((crosstalk.naomi_b_cert))
      NAOMI_B_KEY: ((crosstalk.naomi_b_key))
