groups:
- name: main
  jobs:
  - unit-tests
  - build-sink-controller-image
  - deploy-gke
  - deploy-cfcr
  - gke-tests
  - cfcr-tests
  - promote
- name: release
  jobs:
  - release
  - update-bosh-release

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: vault
  type: docker-image
  source:
    repository: wfernandes/vault-resource
    tag: latest

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: oratos-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master

- name: namespace-drain
  type: git
  source:
    uri: git@github.com:pivotal-cf/namespace-drain
    branch: master
    private_key: ((github.oratos-bot-private-key))

- name: sink-controller-dockerfile
  type: git
  source:
    uri: https://github.com/pivotal-cf/oratos-ci
    branch: master
    paths:
    - docker-images/sink-controller

- name: sink-controller-image
  type: docker-image
  source:
    repository: oratos/sink-controller
    username: ((docker-hub.username))
    password: ((docker-hub.password))

- name: blob-release-image
  type: docker-image
  source:
    repository: oratos/sink-controller
    username: ((docker-hub.username))
    password: ((docker-hub.password))
    tag: v0.4

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack.notifications-url))

- name: oratos-ci-testing-cfcr-bbl-state
  type: vault
  source:
    url: https://vault.oratos.ci.cf-app.com
    role_id: ((vault.role_id))
    secret_id: ((vault.secret_id))
    path: secret/envs/oratos-ci-testing-cfcr-bbl-state
    tarball: true

- name: namespace-drain-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: namespace-drain
    access_token: ((github.oratos-bot-release-access-token))

- name: sink-resources-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/sink-resources-release
    branch: master
    private_key: ((github.oratos-bot-private-key))

- name: sink-resources-github-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: sink-resources-release
    access_token: ((github.oratos-bot-release-access-token))

- name: pks-releng-release-bucket
  type: gcs-resource
  source:
    bucket: oratos-team-test-tile
    json_key: ((pks-releng.gcp-json))
    regexp: releases/*.tgz
jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
    - get: oratos-ci
  - aggregate:
    - task: run-linter
      file: oratos-ci/tasks/golangci-lint-modules/task.yml
      input_mapping:
        source-repo: namespace-drain
      on_failure:
        put: slack-alert
        params:
          text: Namespace Drain Linter failed
    - task: run-tests
      file: oratos-ci/tasks/go-test-with-latest-packages/task.yml
      privileged: true
      input_mapping:
        source-repo: namespace-drain
      params:
        IMPORT_PATH: github.com/pivotal-cf/namespace-drain
        PKGS_HOOK: |
          go list ./... | grep -v vendor | grep -v pkg/client
      on_failure:
        put: slack-alert
        params:
          text: Namespace Drain Unit tests failed
    - task: run-verify-codegen
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: oratos/ci-base
        inputs:
        - name: namespace-drain
        params:
          DEBUG:
        run:
          path: /bin/bash
          args:
          - "-c"
          - |
            #!/bin/bash
            set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

            export GOPATH="$PWD/workspace"
            path=workspace/src/github.com/pivotal-cf/namespace-drain
            mkdir -p "$path"
            cp -r namespace-drain/. "$path/"
            cd "$path"
            hack/verify-codegen.sh
      on_failure:
        put: slack-alert
        params:
          text: Namespace Drain Verify Codegen failed

- name: build-sink-controller-image
  serial: true
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
      passed:
      - unit-tests
    - get: sink-controller-dockerfile
      trigger: true
    - get: oratos-ci
  - task: prepare-build
    file: oratos-ci/tasks/build-go-modules-docker-image/task.yml
    input_mapping:
      source-repo: namespace-drain
    params:
      DOCKERFILE: oratos-ci/docker-images/sink-controller/Dockerfile
  - put: sink-controller-image
    params:
      build: build-image/build
      tag: build-image/tag
      cache: true
      cache_tag: latest
    get_params:
      skip_download: true

- name: deploy-gke
  serial: true
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
      passed:
      - build-sink-controller-image
    - get: sink-controller-image
      trigger: true
      passed:
      - build-sink-controller-image
      params:
        skip_download: true
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      inputs:
      - name: namespace-drain
      - name: sink-controller-image
      params:
        SERVICE_ACCOUNT: ((gcloud.oratos-ci-testing-gke-service-account))
        DEBUG:
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

          echo "$SERVICE_ACCOUNT" > sa.json
          gcloud auth activate-service-account --key-file sa.json
          rm sa.json
          gcloud container clusters get-credentials oratos-ci-testing \
            --zone us-central1-a

          sha="$(cat sink-controller-image/tag)"
          yq read namespace-drain/manifests/05-deployments/sink.yml --tojson | \
            jq '(.spec.template.spec.containers[] | select(.name == "sink-controller")).image = "oratos/sink-controller:'"$sha"'"' \
            > namespace-drain/manifests/05-deployments/sink.json
          rm namespace-drain/manifests/05-deployments/sink.yml
          kubectl apply -R -f namespace-drain/manifests
          patch='{"spec": {"template": {"metadata": {"labels": {"randomversion": "'$RANDOM'"}}}}}'
          kubectl patch -R -f namespace-drain/manifests --patch "$patch"

- name: gke-tests
  serial: true
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
      passed:
      - deploy-gke
    - get: sink-controller-image
      trigger: true
      passed:
      - deploy-gke
      params:
        skip_download: true
  - task: run-crd-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      inputs:
      - name: namespace-drain
      params:
        SERVICE_ACCOUNT: ((gcloud.oratos-ci-testing-gke-service-account))
        DEBUG:
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

          echo "$SERVICE_ACCOUNT" > sa.json
          gcloud auth activate-service-account --key-file sa.json
          rm sa.json
          gcloud container clusters get-credentials oratos-ci-testing \
            --zone us-central1-a

          namespace-drain/tests/test.sh

- name: deploy-cfcr
  serial: true
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
      passed:
      - build-sink-controller-image
    - get: sink-controller-image
      trigger: true
      passed:
      - build-sink-controller-image
      params:
        skip_download: true
    - get: oratos-ci-testing-cfcr-bbl-state
    - get: oratos-ci
  - task: deploy
    input_mapping:
      bbl-state: oratos-ci-testing-cfcr-bbl-state
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      inputs:
      - name: namespace-drain
      - name: sink-controller-image
      - name: oratos-ci
      - name: bbl-state
      params:
        DEBUG:
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

          BBL_STATE_DIR=bbl-state \
              oratos-ci/scripts/cfcr.sh testing get-credentials

          sha="$(cat sink-controller-image/tag)"
          yq read namespace-drain/manifests/05-deployments/sink.yml --tojson | \
            jq '(.spec.template.spec.containers[] | select(.name == "sink-controller")).image = "oratos/sink-controller:'"$sha"'"' \
            > namespace-drain/manifests/05-deployments/sink.json
          rm namespace-drain/manifests/05-deployments/sink.yml
          kubectl apply -R -f namespace-drain/manifests
          patch='{"spec": {"template": {"metadata": {"labels": {"randomversion": "'$RANDOM'"}}}}}'
          kubectl patch -R -f namespace-drain/manifests --patch "$patch"

- name: cfcr-tests
  serial: true
  plan:
  - aggregate:
    - get: namespace-drain
      trigger: true
      passed:
      - deploy-cfcr
    - get: sink-controller-image
      trigger: true
      passed:
      - deploy-cfcr
      params:
        skip_download: true
    - get: oratos-ci
    - get: oratos-ci-testing-cfcr-bbl-state
  - task: crosstalk-test
    file: oratos-ci/tasks/sink-crosstalk/task.yml
    input_mapping:
      bbl-state: oratos-ci-testing-cfcr-bbl-state
    params:
      GET_CREDENTIALS_HOOK: |
        BBL_STATE_DIR=bbl-state \
            oratos-ci/scripts/cfcr.sh testing get-credentials
      NAOMI_A_CERT: ((crosstalk.naomi_a_cert))
      NAOMI_A_KEY: ((crosstalk.naomi_a_key))
      NAOMI_B_CERT: ((crosstalk.naomi_b_cert))
      NAOMI_B_KEY: ((crosstalk.naomi_b_key))

- name: promote
  serial: true
  plan:
  - aggregate:
    - get: sink-controller-image
      trigger: true
      passed:
      - cfcr-tests
      - gke-tests
      params:
        save: true
    - task: write-promote-tag
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: oratos/ci-base
        outputs:
        - name: promote
        params:
          DEBUG:
        run:
          path: /bin/bash
          args:
          - "-c"
          - |
            #!/bin/bash
            set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

            echo "release-elect" > promote/tag
  - put: sink-controller-image
    params:
      load: sink-controller-image
      tag: promote/tag
      cache: true
      cache_tag: latest
    get_params:
      skip_download: true

- name: release
  serial: true
  plan:
  - get: sink-controller-image
  - task: release
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      params:
        # namespace drain
        GIT_REF: 00cbef49ed63ae44147b21d45116590311645342 # ref to use to build the release
        VERSION: v0.4 # version of the release

        # fluent bit
        FLUENT_BIT_OUT_SYSLOG_VERSION: v0.3 # version of the fluent-bit image to use

        DOCKERHUB_USERNAME: ((docker-hub.username))
        DOCKERHUB_PASSWORD: ((docker-hub.password))
        GITHUB_PRIVATE_KEY: ((github.oratos-bot-private-key))
        DEBUG:
      outputs:
      - name: github-release
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "$DEBUG" ] && set -x

          if [ -z "$GIT_REF" ]; then
            echo GIT_REF param required
            exit 1
          fi
          if ! [[ "$VERSION" =~ v ]]; then
            echo VERSION param required to start with v
            exit 1
          fi
          if ! [[ "$FLUENT_BIT_OUT_SYSLOG_VERSION" =~ v ]]; then
            echo FLUENT_BIT_OUT_SYSLOG_VERSION param required to start with v
            exit 1
          fi

          # Note: this was copied from the docker-image-resource
          # https://github.com/concourse/docker-image-resource/blob/c725c6277ca2820016de1bfe2bdfabaad5fd5879/assets/common.sh#L4
          sanitize_cgroups() {
            mkdir -p /sys/fs/cgroup
            mountpoint -q /sys/fs/cgroup || \
              mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup

            mount -o remount,rw /sys/fs/cgroup

            sed -e 1d /proc/cgroups | while read sys hierarchy num enabled; do
              if [ "$enabled" != "1" ]; then
                # subsystem disabled; skip
                continue
              fi

              grouping="$(cat /proc/self/cgroup | cut -d: -f2 | grep "\\<$sys\\>")" || true
              if [ -z "$grouping" ]; then
                # subsystem not mounted anywhere; mount it on its own
                grouping="$sys"
              fi

              mountpoint="/sys/fs/cgroup/$grouping"

              mkdir -p "$mountpoint"

              # clear out existing mount to make sure new one is read-write
              if mountpoint -q "$mountpoint"; then
                umount "$mountpoint"
              fi

              mount -n -t cgroup -o "$grouping" cgroup "$mountpoint"

              if [ "$grouping" != "$sys" ]; then
                if [ -L "/sys/fs/cgroup/$sys" ]; then
                  rm "/sys/fs/cgroup/$sys"
                fi

                ln -s "$mountpoint" "/sys/fs/cgroup/$sys"
              fi
            done

            if ! test -e /sys/fs/cgroup/systemd ; then
              mkdir /sys/fs/cgroup/systemd
              mount -t cgroup -o none,name=systemd none /sys/fs/cgroup/systemd
            fi
          }
          sanitize_cgroups
          service docker start
          function cleanup {
            set +e
            service docker stop
            killall ssh-agent
          }
          trap cleanup EXIT

          echo waiting 10 seconds while docker starts up
          sleep 10

          mkdir -p ~/.ssh/
          ssh-keyscan github.com >> ~/.ssh/known_hosts 2> /dev/null
          eval "$(ssh-agent)"
          set +x
          echo "$GITHUB_PRIVATE_KEY" > key
          [ -n "$DEBUG" ] && set -x
          chmod 0600 key
          ssh-add key
          rm key
          git clone git@github.com:pivotal-cf/namespace-drain
          pushd namespace-drain > /dev/null
            git checkout "$GIT_REF"
            git tag "$VERSION"
          popd > /dev/null

          yq read namespace-drain/manifests/05-deployments/sink.yml --tojson \
            | jq '(.spec.template.spec.containers[] | select(.name == "sink-controller")).image = "oratos/sink-controller:'"$VERSION"'"' \
            > namespace-drain/manifests/05-deployments/sink.json
          yq read namespace-drain/manifests/05-deployments/sink.json \
            > namespace-drain/manifests/05-deployments/sink.yml
          rm namespace-drain/manifests/05-deployments/sink.json

          yq read namespace-drain/manifests/04-daemonsets/fluent-bit.yml --tojson \
            | jq '(.spec.template.spec.containers[] | select(.name == "fluent-bit")).image = "oratos/fluent-bit-out-syslog:'"$FLUENT_BIT_OUT_SYSLOG_VERSION"'"' \
            > namespace-drain/manifests/04-daemonsets/fluent-bit.json
          yq read namespace-drain/manifests/04-daemonsets/fluent-bit.json \
            > namespace-drain/manifests/04-daemonsets/fluent-bit.yml
          rm namespace-drain/manifests/04-daemonsets/fluent-bit.json

          for f in namespace-drain/manifests/**/*; do
            echo ---
            cat "$f";
          done > github-release/manifest.yml
          echo "$VERSION" > github-release/name
          echo "$VERSION" > github-release/tag

          pushd namespace-drain > /dev/null
            git reset --hard HEAD
          popd > /dev/null

          cat <<EOF > github-release/body
          These are the versions of the docker images used in this release:

          - [oratos/sink-controller][sink-controller]:$VERSION
          - [oratos/fluent-bit-out-syslog][fluent-bit-out-syslog]:$FLUENT_BIT_OUT_SYSLOG_VERSION

          [sink-controller]: https://hub.docker.com/r/oratos/sink-controller/
          [fluent-bit-out-syslog]: https://hub.docker.com/r/oratos/fluent-bit-out-syslog/
          EOF

          set +x
          echo "$DOCKERHUB_PASSWORD" \
            | docker login \
              --username "$DOCKERHUB_USERNAME" \
              --password-stdin
          [ -n "$DEBUG" ] && set -x

          docker pull "oratos/sink-controller:$GIT_REF"
          docker tag "oratos/sink-controller:$GIT_REF" \
            "oratos/sink-controller:$VERSION"
          docker tag "oratos/sink-controller:$GIT_REF" \
            "oratos/sink-controller:latest"
          docker push "oratos/sink-controller:$VERSION"
          docker push "oratos/sink-controller:latest"


          pushd namespace-drain > /dev/null
            git push origin --tags
          popd > /dev/null
  - put: namespace-drain-release
    params:
      name: github-release/name
      body: github-release/body
      tag: github-release/tag

      globs:
      - github-release/manifest.yml

- name: update-bosh-release
  plan:
  - get: sink-controller-image
    trigger: true
    passed:
    - release
  - get: oratos-ci
  - get: sink-resources-release
  - get: blob-release-image
    params:
      save: true
  - task: update-bosh-release
    file: oratos-ci/tasks/update-bosh-release/task.yml
    params:
      BLOB_NAME: oratos_sink-controller
      PRIVATE_YML: ((release.private_yml))
  - put: pks-releng-release-bucket
    params:
      file: bosh-release/binaries/*.tgz
  - put: sink-resources-release
    params:
      repository: put-sink-resources-release
      name: bosh-release/name
  - put: sink-resources-github-release
    params:
      name: bosh-release/name
      tag: bosh-release/tag
      globs:
      - bosh-release/binaries/*.tgz
