groups:
- name: crfr-testing
  jobs:
  - oratos-ci-testing-cfcr-bbl-up
  - oratos-ci-testing-cfcr-bbl-destroy

resource_types:
- name: vault
  type: docker-image
  source:
    repository: oratos/vault-resource
    tag: latest

resources:
- name: oratos-ci-testing-cfcr-bbl-state
  type: vault
  source:
    url: https://vault.oratos.ci.cf-app.com
    role_id: ((vault.role_id))
    secret_id: ((vault.secret_id))
    path: secret/envs/oratos-ci-testing-cfcr-bbl-state
    tarball: true

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    branch: v10.16.0

jobs:
- name: oratos-ci-testing-cfcr-bbl-up
  serial: true
  serial_groups:
  - oratos-ci-testing-cfcr-director-lifecycle
  plan:
  - in_parallel:
    - get: oratos-ci-testing-cfcr-bbl-state
    - get: cf-deployment-concourse-tasks
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    input_mapping:
      bbl-state: oratos-ci-testing-cfcr-bbl-state
      bbl-config: oratos-ci-testing-cfcr-bbl-state
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcloud.oratos-ci-testing-cfcr-service-account))
      BBL_GCP_REGION: us-central1
      BBL_ENV_NAME: oratos-ci-testing
      SKIP_LB_CREATION: true
      STORE_BBL_STATE_AS_TARBALL: true
  - task: clean-up-bbl-state
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      inputs:
      - name: updated-bbl-state
      outputs:
      - name: cleaned-bbl-state
      params:
        DEBUG:
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

          tar xvzf updated-bbl-state/bbl-state.tgz -C updated-bbl-state/
          rm updated-bbl-state/bbl-state.tgz

          pushd updated-bbl-state/bbl-state > /dev/null
            # Delete all files ignored by git.
            git init
            git clean -ffdX
          popd > /dev/null

          cp -r updated-bbl-state/. cleaned-bbl-state
  - put: oratos-ci-testing-cfcr-bbl-state
    params:
      data: updated-bbl-state
  - task: upload-bosh-stemcell
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oratos/ci-base
      inputs:
      - name: oratos-ci-testing-cfcr-bbl-state
      params:
        DEBUG:
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

          pushd oratos-ci-testing-cfcr-bbl-state/bbl-state > /dev/null
            eval "$(bbl print-env)"
          popd > /dev/null

          bosh upload-stemcell --sha1 3148f41b46af04e23695d9c0a48e8d66b1c1c34e https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-xenial-go_agent?v=250.23

- name: oratos-ci-testing-cfcr-bbl-destroy
  serial: true
  serial_groups:
  - oratos-ci-testing-cfcr-director-lifecycle
  plan:
  - in_parallel:
    - get: oratos-ci-testing-cfcr-bbl-state
    - get: cf-deployment-concourse-tasks
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: oratos-ci-testing-cfcr-bbl-state
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcloud.oratos-ci-testing-cfcr-service-account))
  - put: oratos-ci-testing-cfcr-bbl-state
    params:
      data: updated-bbl-state
