#!/bin/bash
set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

release_file="sink-resources-release.tgz"

git clone sink-resources-release put-sink-resources-release
pushd put-sink-resources-release
  echo "$PRIVATE_YML" > config/private.yml

  bosh sync-blobs

  echo "Clean old blobs"
  for b in $(bosh blobs --column="Path"); do
    echo "bosh remove-blob $b"
    bosh remove-blob "$b"
  done

  echo "Begin blob management"
  for file in ../sink-resources-github-release/*.tgz ../observability-manager-github-release/*.tgz; do
    file_name=${file##*/}
    bosh add-blob "${file}" "container-images/${file_name}"
  done

  bosh upload-blobs

  echo "Create final release"
  bosh --non-interactive create-release \
       --final \
       --force \
       --tarball="${release_file}"

  SINK_RESOURCES_RELEASE_VERSION=$(yq r releases/sink-resources-release/index.yml --tojson \
                | jq -r ".builds[].version" \
                | sort --version-sort \
                | tail -n1)

  # Generate OSL config
  for f in blobs/container-images/*.tgz; do
    docker load --input "$f"
  done
  ./scripts/generate-osl-deps.sh

  echo "Move build ${release_file} - ${SINK_RESOURCES_RELEASE_VERSION} to bosh-release/binaries"
  mkdir -p ../bosh-release/binaries
  mv "${release_file}" "../bosh-release/binaries/sink-resources-release-${SINK_RESOURCES_RELEASE_VERSION}.tgz"

  echo "Copy OSL config sink-resources-${SINK_RESOURCES_RELEASE_VERSION}.yml to bosh-release/binaries"
  cp "osl/${SINK_RESOURCES_RELEASE_VERSION}/sink-resources-${SINK_RESOURCES_RELEASE_VERSION}.yml" \
      "../bosh-release/binaries/sink-resources-${SINK_RESOURCES_RELEASE_VERSION}.yml"

  git add .
  git commit -m"CI bump sink resource release to ${SINK_RESOURCES_RELEASE_VERSION}"
popd

echo "$SINK_RESOURCES_RELEASE_VERSION" > bosh-release/name
echo "$SINK_RESOURCES_RELEASE_VERSION" > bosh-release/tag

ls -alth bosh-release/binaries
