---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mesosphere/aws-cli

inputs:
- name: oratos-ci # - This repo
- name: lb-ip

run:
  path: oratos-ci/tasks/configure-dev-dns-zone/task

params:
  # - Required
  # - The access key ID for the dev dns account.
  AWS_ACCESS_KEY_ID:

  # - Required
  # - The secret access key for the dev dns account.
  AWS_SECRET_ACCESS_KEY:

  # - Required
  # - The FQ hostname for the environment.
  ENV_DNS_NAME:

  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
