#!/bin/bash
set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

mkdir -p ~/.ssh/
ssh-keyscan github.com >> ~/.ssh/known_hosts 2> /dev/null

pushd source-repo > /dev/null
  go mod download
  golangci-lint run --deadline 20m ./...
popd > /dev/null
