#!/bin/bash
set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

mkdir -p ~/.ssh/
ssh-keyscan github.com >> ~/.ssh/known_hosts 2> /dev/null

export GOFLAGS="-mod=vendor"

pushd source-repo > /dev/null
  ./tests/run-linter.sh
popd > /dev/null
