---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: oratos/ci-base

inputs:
- name: oratos-ci   # - This repo
- name: source-repo # - The Go package to test

run:
  path: oratos-ci/tasks/golangci-lint-modules/task

params:
  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
