platform: linux
image_resource:
  type: docker-image
  source:
    repository: oratos/ci-base
inputs:
- name: oratos-ci
params:
  # - Optional
  # - gcloud service account details
  SERVICE_ACCOUNT:

  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
run:
  path: oratos-ci/tasks/clean-up-gke/task
