#!/bin/bash
set -Eeuo pipefail; [ -n "${DEBUG:-}" ] && set -x

source "oratos-ci/scripts/test/common.sh"

function validate {
    ensure_variable_isset "$GET_CREDENTIALS_HOOK" "GET_CREDENTIALS_HOOK"
}

function delete_old_jobs {
    kubectl delete jobs --all --namespace pks-system
    echo "Completed deleting all jobs in pks-system namespace"
}

function roll {
    kubectl delete pods --all --namespace pks-system
    echo "Completed rolling all the pods in pks-system namespace"
}

function apply_manifests {
    observability_manager_digest="$(cat observability-manager-image/digest)"
    pushd sink-resources/manifests/observability-manager
        kustomize edit set imagetag "oratos/observability-manager@$observability_manager_digest"
    popd

    # Using $RANDOM for sink resources version to ensure cert-generator job is
    # always ran.
    kustomize build sink-resources/manifests/observability-manager | kubectl apply -f -
    echo "Completed applying the manifests for sink-resources/pks"
}

function verify_resources_are_running {
    # Just wait for some time to increase the chances of the sink-resources to
    # come up. TODO: Remove this eventually.
    sleep 10

    # Verify sink resources are healthy
    verify_deployment_running "app=sink-controller"
    verify_deployment_running "app=event-controller"
    verify_deployment_running "app=metric-controller"
    verify_deployment_running "app=validator"

    verify_daemonset_running "app=fluent-bit"
    verify_daemonset_running "app=telegraf"
}

function main {
    validate
    login_to_cluster_as_admin
    delete_old_jobs
    apply_manifests
    roll
    verify_resources_are_running
}

main
