platform: linux
image_resource:
  type: docker-image
  source:
    repository: oratos/ci-base
inputs:
- name: sink-resources
- name: sink-controller-image
- name: event-controller-image
- name: metric-controller-image
- name: cert-generator-image
- name: ghostunnel-image
- name: fluent-bit-out-syslog-image
- name: validator-image
- name: sink-state-updater-image
- name: telegraf-image
- name: oratos-ci
- name: bbl-state # only needed for cfcr clusters
params:
  # - Required
  # - Code to run to setup kubectl to point to the cluster.
  GET_CREDENTIALS_HOOK:

  # - Optional
  # - gcloud service account details
  SERVICE_ACCOUNT:

  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:

  # - Optional
  # - Number of times to poll to verify resources are running
  POLLING_COUNT: 12
run:
  path: oratos-ci/tasks/deploy-sink-resources/task
