platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
- name: oratos-ci
- name: bbl-state
params:
  # - Required
  # - Code to run to setup kubectl to point to the cluster.
  GET_CREDENTIALS_HOOK:

  # - Required
  # - Used when reporting to datadog.
  SYSTEM_DOMAIN:

  # - Required
  # - The API Key to send metrics to DataDog.
  DATADOG_API_KEY:

  # - Optional
  # - How many logs to emit.
  CYCLES: 10000

  # - Optional
  # - The delay between emitting each log.
  DELAY: 20

  # - Optional
  # - The unit of the delay.
  DELAY_UNIT: ms

  # - Optional
  # - The message to write in the logs
  MESSAGE:

  # - Optional
  # - Wait sleeps for N seconds waiting for messages to show up.
  WAIT: 300

  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:
run:
  path: oratos-ci/tasks/loggregator-rlp-blackbox/task
