#!/bin/bash

set -ex
REMAPPER="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/osstp.yaml

pip install -r osstpclients/etc/requirements.txt
OSSTP_LOAD="osstpclients/bin/osstp-load.py"
OSM_API_CREDENTIALS_FILE=$(mktemp)
echo "$OSM_API_CREDENTIALS" > "$OSM_API_CREDENTIALS_FILE"

pushd osl-packages
    ls
popd

pushd sink-resources
    osstptool generate -e sink-resources github.com/pivotal-cf/sink-resources --remapper-definitions-file="$REMAPPER"
    python "$OSSTP_LOAD" -R sink-resources-release/latest <change_me> -I "Distributed - Static Link w/ TP" -A "$OSM_API_CREDENTIALS_FILE"
popd

