#!/bin/bash

set -ex
HOME_GLOB="/tmp/build/*"
# shellcheck disable=SC2086
HOME_DIR=$(cd ${HOME_GLOB} && pwd)
REMAPPER="${HOME_DIR}/oratos-ci/scripts/osstp.yaml"
pip install -r osstpclients/etc/requirements.txt
OSSTP_LOAD="${HOME_DIR}/osstpclients/bin/osstp-load.py"
OSM_API_CREDENTIALS_FILE=$(mktemp)
echo "$OSM_API_CREDENTIALS" > "$OSM_API_CREDENTIALS_FILE"

pushd osstptool
    make
popd

osl_packages=("ghostunnel" "cert-generator" "event-controller" "sink-controller" "telegraf" "validator" "metric-controller" "observability-manager")

for component in "${osl_packages[@]}"; do
    echo "y" | python "$OSSTP_LOAD" -R sink-resources-release/latest "${HOME_DIR}/${component}-pkg-list/${component}" -I "Distributed - Static Link w/ TP" -A "$OSM_API_CREDENTIALS_FILE"
done;

pushd sink-resources
    "${HOME_DIR}/osstptool/osstptool" generate -e sink-resources github.com/pivotal-cf/sink-resources --remapper-definitions-file="$REMAPPER"
    echo "y" | python "$OSSTP_LOAD" -R sink-resources-release/latest osstp_golang.yml -I "Distributed - Static Link w/ TP" -A "$OSM_API_CREDENTIALS_FILE"
popd

pushd fluent-bit-out-syslog
    "${HOME_DIR}/osstptool/osstptool" generate --vendor-path=vendor fluent-bit-out-syslog github.com/pivotal-cf/fluent-bit-out-syslog --remapper-definitions-file="$REMAPPER"
    echo "y" | python "$OSSTP_LOAD" -R sink-resources-release/latest osstp_golang.yml -I "Distributed - Static Link w/ TP" -A "$OSM_API_CREDENTIALS_FILE"
popd
