platform: linux
image_resource:
  type: docker-image
  source:
    repository: oratos/ci-base
inputs:
- name: source-repo # repo to build static binaries from
- name: oratos-ci # repo for task file
outputs:
- name: build-image # the place to store the build context and tag
params:
  # - Required
  # - Override default args with private artifacts in all docker builds
  BASE_IMAGE:
  GOLANG_SOURCE:
  KUBECTL_SOURCE:

  # - Optional
  # - Provide a path to inside the source repo where the docker context lives.
  SOURCE_PATH:

  # - Optional
  # - Provide a path to the Dockerfile if it is not in the source repo.
  DOCKERFILE:

  # - Optional
  # - Set to true to output all commands that are ran.
  DEBUG:

  # - Optional
  # - Set to the docker repository for telegraf image
  CONTAINER_REPOSITORY: oratos
run:
  path: oratos-ci/tasks/build-docker-image/task
