platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-releng-environments/concourse/docker-image-resource
inputs:
- name: image-repo # repo to build static binaries from
- name: oratos-ci # repo for task file
outputs:
- name: image-tarball # the place to store the build context and tag
- name: pkg-list # the place to store the /builder-pkg-list for OSL process
params:
  # - Required
  # - Override default args with private artifacts in all docker builds
  BASE_IMAGE:
  GOLANG_SOURCE:
  KUBECTL_SOURCE:
  COMPONENT:

  # - Required
  # - Set to the docker repository
  CONTAINER_REPOSITORY: oratos
  DOCKERHUB_USERNAME:
  DOCKERHUB_PASSWORD:

  DOCKER_FILE_PATH: 
run:
  path: oratos-ci/tasks/build-docker-image/task
