#!/bin/bash

# shellcheck disable=SC1091
source "/opt/resource/common.sh"
start_docker 3 3
log_in "$DOCKERHUB_USERNAME" "$DOCKERHUB_PASSWORD" "$CONTAINER_REPOSITORY"

# compute sha for tagging the docker image
sha="$(cat image-repo/.git/HEAD)"
image_name="$CONTAINER_REPOSITORY/$COMPONENT:$sha"

echo "base image:"$BASE_IMAGE

pushd image-repo
  docker build \
    --build-arg BASE_IMAGE="$BASE_IMAGE" \
    --build-arg TELEGRAF_IMAGE="$CONTAINER_REPOSITORY/telegraf:$sha" \
    --build-arg GOLANG_SOURCE="$GOLANG_SOURCE" \
    --build-arg KUBECTL_SOURCE="$KUBECTL_SOURCE" \
    -f "$DOCKER_FILE_PATH" \
    . \
    -t "$image_name"
  docker push $image_name
popd

docker save "$image_name" | gzip > "image-tarball/$COMPONENT-$sha.tgz"

if [[ "${image_name}" ==  *node-exporter* ]]
then
  docker run -t "$image_name" &
  sleep 5
  echo "test001: "$(docker ps)
  container_id=$(docker ps | grep "$image_name" | awk '{print $1}')
  echo "test002: "$(container_id)
  docker cp "${container_id}":/builder-dpkg-list pkg-list/"${COMPONENT}"
  sleep 2
  echo "test003: "
  cat pkg-list/"${COMPONENT}"
else
  docker run -t "$image_name" cat /builder-dpkg-list > pkg-list/"${COMPONENT}"
fi
